import {Blob} from 'node:buffer';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {environment} from './logic-dom.mjs';
export async function runTests(){
  const root=new URL('../',import.meta.url);let passed=0;
  const source=await readFile(new URL('src/core.js',root),'utf8');const game=await readFile(new URL('src/game.js',root),'utf8');
  const ctx=vm.createContext({module:{exports:{}},console});vm.runInContext(source,ctx);const B=ctx.module.exports;
  const test=(name,fn)=>{try{fn();passed++}catch(err){err.message=name+': '+err.message;throw err}};
  test('Single answer',()=>{const q=B.question();assert(B.check(q,q.options[0].id));assert(!B.check(q,q.options[1].id))});
  test('Multiple exact set, independent of order',()=>{const q=B.question('multiple');q.options[1].correct=true;assert(B.check(q,[q.options[1].id,q.options[0].id]));assert(!B.check(q,[q.options[0].id]));assert(!B.check(q,q.options.map(o=>o.id)))});
  test('Text alternatives, spaces and case',()=>{const q=B.question('text');q.answers=['Hello world','привет'];assert(B.check(q,' HELLO   world '));assert(B.check(q,'Привет'));q.caseSensitive=true;assert(!B.check(q,'HELLO world'))});
  test('Numeric tolerance excludes empty and invalid input',()=>{const q=B.question('text');q.answers=['10'];q.tolerance=.5;assert(B.check(q,'10.4'));assert(!B.check(q,'10.6'));assert(!B.check(q,''));assert(!B.check(q,'abc'))});
  test('Oral and stable order IDs',()=>{const q=B.question('order');assert(B.check(q,q.options.map(o=>o.id)));assert(!B.check(q,[...q.options].reverse().map(o=>o.id)));assert(B.check(B.question('oral'),true));assert(!B.check(B.question('oral'),false))});
  test('Valid defaults and JSON round trip',()=>{const p=B.defaults();assert.equal(B.validate(p).length,0);assert.equal(JSON.stringify(B.load(JSON.parse(JSON.stringify(p)))),JSON.stringify(p))});
  test('Invalid questions rejected by validation',()=>{const p=B.defaults();p.questions[0].options[1].correct=true;assert(B.validate(p).length>0);p.questions=[];assert(B.validate(p).length>0)});
  test('Executable or external media rejected',()=>{const p=B.defaults();p.assets.bad={data:'data:image/svg+xml;base64,PHN2Zz4='};assert.throws(()=>B.load(p));p.assets.bad={data:'https://example.test/x.png'};assert.throws(()=>B.load(p));assert.throws(()=>B.load({schemaVersion:99}))});
  test('GIF preservation and pruning',()=>{const p=B.defaults();p.assets.gif={name:'a.gif',type:'image/gif',data:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==',size:34,originalSize:34};p.player.idle='gif';p.assets.unused={...p.assets.gif};const c=B.compact(p);assert.equal(Object.keys(c.assets).join(','),'gif');assert.equal(B.load(c).assets.gif.data,p.assets.gif.data)});
  test('HTML escaping',()=>assert.equal(B.escape('</script><img onerror="x">'),'&lt;/script&gt;&lt;img onerror=&quot;x&quot;&gt;'));
  function mount(p){const dom=environment();const context=vm.createContext(dom.env);vm.runInContext(source+'\n'+game+'\nthis.app=mountBasketball(document.body,JSON.parse('+JSON.stringify(JSON.stringify(p))+'));',context);return {...dom,context,app:context.app}}
  test('Win, score, bonus and replay',()=>{const p=B.defaults();p.titleScreen.enabled=false;p.audio.effects=false;p.scoring.bonusEvery=1;p.questions=[p.questions[0]];const dom=mount(p);let input=dom.document.body.querySelectorAll('input').find(i=>i.value===p.questions[0].options[0].id);input.checked=true;input.onchange();dom.document.body.querySelector('form').onsubmit({preventDefault(){}});dom.advanceFrames();assert.equal(dom.document.body.querySelector('.game-feedback').textContent.includes('Верно'),true);dom.document.body.querySelector('.game-feedback').querySelector('button').click();assert.match(dom.document.body.textContent,/Отличная игра/);assert.match(dom.document.body.textContent,/Очки: 20/);dom.document.body.querySelector('.game-cover').querySelector('button').click();assert.match(dom.document.body.querySelector('.game-hud').textContent,/★ 0/);dom.app.destroy();assert.equal(dom.timers.size,0)});
  test('Wrong answer loses a life and defeats at zero',()=>{const p=B.defaults();p.titleScreen.enabled=false;p.audio.effects=false;p.scoring.lives=1;const dom=mount(p);const inputs=dom.document.body.querySelectorAll('input');inputs.find(i=>i.value!==p.questions[0].options[0].id).onchange();dom.document.body.querySelector('form').onsubmit({preventDefault(){}});dom.advanceFrames();dom.document.body.querySelector('.game-feedback').querySelector('button').click();assert.match(dom.document.body.textContent,/Попробуем ещё раз/);assert.match(dom.document.body.textContent,/♥ 0/);dom.app.destroy()});
  test('Double submit is blocked',()=>{const p=B.defaults();p.titleScreen.enabled=false;p.audio.effects=false;p.questions=[p.questions[0]];const dom=mount(p);const input=dom.document.body.querySelectorAll('input').find(i=>i.value===p.questions[0].options[0].id);input.onchange();const form=dom.document.body.querySelector('form');form.onsubmit({preventDefault(){}});form.onsubmit({preventDefault(){}});assert.match(dom.document.body.querySelector('.game-hud').textContent,/★ 10/);dom.app.destroy()});
  test('Timer and pause',()=>{const p=B.defaults();p.titleScreen.enabled=false;p.audio.effects=false;p.scoring.timer=true;p.scoring.seconds=30;const dom=mount(p);const interval=[...dom.timers.values()][0];dom.document.body.querySelector('.game-controls').querySelector('button').click();interval();assert.match(dom.document.body.querySelector('.game-hud').textContent,/0:30/);dom.document.body.querySelector('.pause-overlay').querySelector('button').click();interval();assert.match(dom.document.body.querySelector('.game-hud').textContent,/0:29/);dom.app.destroy();assert.equal(dom.timers.size,0)});
  test('All remaining question types execute in the game',()=>{for(const type of ['multiple','text','oral','order']){const p=B.defaults(),q=B.question(type);p.titleScreen.enabled=false;p.audio.effects=false;p.questions=[q];const dom=mount(p),body=dom.document.body;const form=body.querySelector('form');if(type==='multiple'){const input=body.querySelectorAll('input').find(x=>x.value===q.options[0].id);input.checked=true;input.onchange();form.onsubmit({preventDefault(){}})}if(type==='text'){body.querySelector('input').value='Ответ';form.onsubmit({preventDefault(){}})}if(type==='oral'){form.querySelector('button').click()}if(type==='order'){for(let i=0;i<q.options.length;i++){for(let j=0;j<q.options.length;j++){const list=body.querySelector('.order-list');const rows=list.children;const current=rows.findIndex(row=>row.textContent.includes(q.options[i].text));if(current<=i)break;rows[current].querySelectorAll('button')[0].click()}}form.onsubmit({preventDefault(){}})}dom.advanceFrames();assert.match(body.querySelector('.game-feedback').textContent,/Верно/);dom.app.destroy()}});
  test('Total timer resets after life timeout',()=>{const p=B.defaults();p.titleScreen.enabled=false;p.audio.effects=false;p.scoring.timer=true;p.scoring.timerMode='total';p.scoring.seconds=30;const dom=mount(p),interval=[...dom.timers.values()][0];for(let i=0;i<30;i++)interval();dom.advanceFrames();dom.document.body.querySelector('.game-feedback').querySelector('button').click();assert.match(dom.document.body.querySelector('.game-hud').textContent,/0:30/);assert.match(dom.document.body.querySelector('.game-hud').textContent,/♥ 2/);dom.app.destroy()});
  test('Reduced motion completes result',()=>{const p=B.defaults();p.titleScreen.enabled=false;p.audio.effects=false;p.accessibility.reducedMotion=true;const dom=mount(p);dom.document.body.querySelectorAll('input').find(i=>i.value===p.questions[0].options[0].id).onchange();dom.document.body.querySelector('form').onsubmit({preventDefault(){}});dom.advanceFrames();assert(dom.document.body.querySelector('.game-feedback').querySelector('button'));dom.app.destroy()});
  const html=await readFile(new URL('index.html',root),'utf8');
  const dom=environment();const body=html.match(/<body>([\s\S]*?)<script>/)[1];dom.parseHTML(dom.document.body,body);const context=vm.createContext(dom.env);for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(match[1],context);
  test('Editor initialization and all panels',()=>{assert(dom.document.getElementById('settings').textContent.includes('Язык игры'));const tabs=dom.document.getElementById('tabs');for(const name of ['title','scene','player','equipment','questions','style','scoring','audio','final','accessibility','export','project']){tabs.onclick({target:{dataset:{tab:name}}});assert(dom.document.getElementById('settings').textContent.length>20)}});
  test('Question creation, undo and redo',()=>{const tabs=dom.document.getElementById('tabs');tabs.onclick({target:{dataset:{tab:'questions'}}});const before=dom.document.getElementById('settings').querySelectorAll('[data-question]').length;dom.document.getElementById('settings').querySelector('[data-action="add-question"]').click();assert.equal(dom.document.getElementById('settings').querySelectorAll('[data-question]').length,before+1);dom.document.getElementById('undo').click();assert.equal(dom.document.getElementById('settings').querySelectorAll('[data-question]').length,before);dom.document.getElementById('redo').click();assert.equal(dom.document.getElementById('settings').querySelectorAll('[data-question]').length,before+1);dom.document.getElementById('undo').click()});
  test('Object drag, resize and undo',()=>{dom.document.getElementById('tabs').onclick({target:{dataset:{tab:'player'}}});let hero=dom.document.body.querySelector('.object-player');hero.onpointerdown({button:0,clientX:0,clientY:0,pointerId:1,target:hero,preventDefault(){}});hero.dispatch('pointermove',{clientX:20,clientY:10});hero.dispatch('pointerup');const x=dom.document.getElementById('inspector').querySelector('[data-path="scene.objects.0.x"]');assert.equal(Number(x.value),125);hero=dom.document.body.querySelector('.object-player');const handle=hero.querySelector('[data-corner="se"]');hero.onpointerdown({button:0,clientX:0,clientY:0,pointerId:2,target:handle,preventDefault(){}});hero.dispatch('pointermove',{clientX:25,clientY:25,shiftKey:false});hero.dispatch('pointerup');assert.equal(Number(dom.document.getElementById('inspector').querySelector('[data-path="scene.objects.0.w"]').value),180);dom.document.getElementById('undo').click();assert.equal(Number(dom.document.getElementById('inspector').querySelector('[data-path="scene.objects.0.w"]').value),155);dom.document.getElementById('undo').click()});
  dom.document.getElementById('export-html').click();const exported=await dom.downloads.find(d=>d.blob)?.blob.text();
  test('Export is standalone and excludes editor and unused languages',()=>{assert(exported);assert(!exported.includes('Мастерская учебных игр'));assert(!exported.includes('Все права защищены'));assert(!exported.includes('https://'));assert(!exported.includes('Deutsch'));assert.match(exported,/mountBasketball/);const gdom=environment(),c=vm.createContext(gdom.env);const rootEl=gdom.document.createElement('main');rootEl.id='game';gdom.document.body.append(rootEl);vm.runInContext(exported.match(/<script>([\s\S]*?)<\/script>/)[1],c);assert.match(gdom.document.body.textContent,/Каждый ответ/)});
  // Verify HTML script boundary safety with hostile author text.
  dom.document.getElementById('tabs').onclick({target:{dataset:{tab:'title'}}});const title=dom.document.getElementById('settings').querySelector('[data-path="titleScreen.title"]');title.value='</script><img src=x onerror=alert(1)>';title.dispatch('input');dom.document.getElementById('export-html').click();const hostile=await dom.downloads.filter(d=>d.blob).at(-1).blob.text();
  test('Author text cannot break exported script boundary',()=>{assert.equal([...hostile.matchAll(/<\/script>/g)].length,1);assert(!hostile.includes('<img src=x onerror'));assert(hostile.includes('\\u003c/script>'))});
  dom.document.getElementById('optimize').click();dom.document.getElementById('export-html').click();const light=await dom.downloads.filter(d=>d.blob).at(-1).blob.text();
  test('Optimized export executes',()=>{const gdom=environment(),c=vm.createContext(gdom.env);const rootEl=gdom.document.createElement('main');rootEl.id='game';gdom.document.body.append(rootEl);vm.runInContext(light.match(/<script>([\s\S]*?)<\/script>/)[1],c);assert.match(gdom.document.body.textContent,/onerror=alert/) });
  return {passed,exportBytes:new Blob([exported]).size,editorBytes:new Blob([html]).size};
}
