(() => {
  'use strict';
  const B=Basketball,$=id=>document.getElementById(id),e=B.escape;
  let project=B.defaults(),tab='project',selected='player',selectedQ=project.questions[0].id,testing=false,game=null,history=[],future=[],autosaveTimer=null,db=null,saveQueue=Promise.resolve(),revision=0;
  const sections={project:'Проект',title:'Титульный лист',scene:'Игровая площадка',player:'Герой',equipment:'Кольцо и мяч',questions:'Задания',style:'Стиль заданий',scoring:'Жизни, таймер, бонусы',audio:'Звуки',final:'Финальные экраны',accessibility:'Доступность',export:'Экспорт'};
  const soundEvents={question:'Задание',correct:'Верно',wrong:'Неверно',throw:'Бросок',swish:'Попадание',miss:'Промах',life:'Потеря жизни',bonus:'Бонус',win:'Победа',lose:'Поражение',music:'Музыка'};
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6000)}
  function get(path){return path.split('.').reduce((v,k)=>v?.[k],project)}
  function set(path,value){const keys=path.split('.'),last=keys.pop();let cur=project;keys.forEach(k=>cur=cur[k]);cur[last]=value}
  function commit(){history.push(B.clone(project));if(history.length>80)history.shift();future=[];revision++;buttons()}
  function buttons(){$('undo').disabled=!history.length||testing;$('redo').disabled=!future.length||testing;$('test').disabled=testing;$('preview').disabled=!testing}
  function changed(rebuild=false){scheduleSave();renderPreview();renderInspector();size();if(rebuild)renderSettings()}
  function scheduleSave(){clearTimeout(autosaveTimer);if(project.meta.autosave)autosaveTimer=setTimeout(()=>persist(),650);else $('save-status').textContent='Автосохранение выключено'}
  function persist(){if(!db)return;$('save-status').textContent='Сохраняю…';const snapshot=B.clone(project);saveQueue=saveQueue.then(()=>new Promise(resolve=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(snapshot,'current');tx.oncomplete=()=>{$('save-status').textContent='Сохранено на этом устройстве · '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});resolve()};tx.onerror=()=>{$('save-status').textContent='Не удалось сохранить: скачайте JSON-проект';resolve()}}))}
  function undo(){if(testing||!history.length)return;future.push(B.clone(project));project=history.pop();revision++;renderAll();scheduleSave()}
  function redo(){if(testing||!future.length)return;history.push(B.clone(project));project=future.pop();revision++;renderAll();scheduleSave()}
  const field=(label,path,type='text',extra='')=>`<label class="field"><span>${e(label)}</span><input type="${type}" data-path="${e(path)}" value="${e(get(path))}" ${extra}></label>`;
  const area=(label,path)=>`<label class="field"><span>${e(label)}</span><textarea data-path="${e(path)}">${e(get(path))}</textarea></label>`;
  const check=(label,path)=>`<label class="checkfield"><input type="checkbox" data-path="${e(path)}" ${get(path)?'checked':''}><span>${e(label)}</span></label>`;
  const select=(label,path,items)=>`<label class="field"><span>${e(label)}</span><select data-path="${e(path)}">${Object.entries(items).map(([k,v])=>`<option value="${e(k)}" ${get(path)===k?'selected':''}>${e(v)}</option>`).join('')}</select></label>`;
  const help=text=>`<p class="help">${e(text)}</p>`;
  function media(label,path,audio=false){const id=get(path),a=project.assets[id];return `<div class="media-field"><strong>${e(label)}</strong>${a?`<div class="media-row">${!audio?`<img src="${e(a.data)}" alt="" class="media-thumb">`:''}<span class="media-name">${e(a.name)} · ${formatBytes(a.size)}<br>До: ${formatBytes(a.originalSize)}</span><button type="button" data-clear-media="${e(path)}" aria-label="Удалить ${e(label)}">×</button></div>`:''}<input type="file" data-media="${e(path)}" accept="${audio?'audio/mpeg,audio/wav,audio/ogg,.mp3,.wav,.ogg':'image/png,image/jpeg,image/webp,image/gif'}"></div>`}
  function renderSettings(){
    $('tabs').innerHTML=Object.entries(sections).map(([k,label])=>`<button type="button" data-tab="${k}" class="${tab===k?'active':''}" aria-pressed="${tab===k}">${label}</button>`).join('');
    let h=`<h2>${sections[tab]}</h2>`;
    if(tab==='project')h+=select('Язык игры','language',B.languages)+help('Переводятся системные кнопки и подсказки. Ваши задания остаются на исходном языке.')+field('Название проекта','meta.name')+field('Громкость, %','audio.volume','range','min="0" max="100"')+check('Звуковые эффекты','audio.effects')+check('Фоновая музыка','audio.music')+check('Автосохранение на устройстве','meta.autosave')+select('Качество изображений','meta.quality',{balanced:'Оптимальное · 1600 px',high:'Высокое · 2400 px',small:'Компактное · 1000 px'})+help('Работает без сервера и подключения к сети. Для переноса проекта на другой компьютер сохраните JSON.');
    if(tab==='title')h+=check('Показывать перед игрой','titleScreen.enabled')+area('Название','titleScreen.title')+area('Подзаголовок','titleScreen.subtitle')+area('Правила','titleScreen.rules')+field('Кнопка (пусто = перевод)','titleScreen.button')+field('Цвет фона','titleScreen.color','color')+field('Цвет текста','titleScreen.textColor','color')+select('Шрифт','titleScreen.fontFamily',{Arial:'Arial',Georgia:'Georgia',Verdana:'Verdana'})+field('Размер заголовка','titleScreen.titleSize','number','min="24" max="86"')+field('Размер подзаголовка','titleScreen.subtitleSize','number','min="16" max="40"')+media('Фон / GIF','titleScreen.background');
    if(tab==='scene'){h+=field('Цвет зала','scene.color','color')+field('Цвет площадки','scene.floor','color')+field('Прозрачность покрытия площадки','scene.floorOpacity','range','min="0" max="1" step="0.05"')+check('Разметка площадки','scene.lines')+field('Затемнение','scene.dimming','range','min="0" max="0.85" step="0.05"')+media('Фон площадки / GIF','scene.background')+'<h3>Объекты сцены</h3><div class="object-list">'+project.scene.objects.map(o=>`<button data-object="${e(o.id)}" class="${selected===o.id?'selected':''}">${e(o.name)} ${o.locked?'🔒':''} ${o.hidden?'(скрыт)':''}</button>`).join('')+'</div><div class="panel-actions"><button data-action="add-decor">+ Декорация</button></div>'+help('Выберите объект и двигайте его на сцене. Зелёные маркеры меняют размер. Shift сохраняет пропорции.');const i=project.scene.objects.findIndex(o=>o.id===selected);if(i>=0)h+=media('Изображение выбранного объекта',`scene.objects.${i}.asset`)}
    if(tab==='player'){const i=project.scene.objects.findIndex(o=>o.id==='player');h+=field('Имя героя','player.name')+check('Отразить героя',`scene.objects.${i}.flip`)+media('Герой: обычное состояние','player.idle')+media('Правильный ответ: GIF / изображение','player.success')+media('Неверный ответ: GIF / изображение','player.miss')+help('Без загрузки используется встроенный игрок. Размер и положение меняются на сцене и в инспекторе.');}
    if(tab==='equipment'){for(const id of ['hoop','ball']){const i=project.scene.objects.findIndex(o=>o.id===id);h+=`<h3>${id==='hoop'?'Кольцо':'Мяч'}</h3><button data-object="${id}">Выбрать на сцене</button>`+media('Своё изображение',`scene.objects.${i}.asset`)}h+=field('Точка попадания X (доля ширины кольца)','hoop.targetX','number','min="0" max="1" step="0.01"')+field('Точка попадания Y (доля высоты)','hoop.targetY','number','min="0" max="1" step="0.01"')+field('Скорость броска','ball.speed','range','min="0.5" max="2.5" step="0.1"')+field('Высота дуги, px','ball.arc','range','min="50" max="350" step="10"')}
    if(tab==='questions')h+=questionsPanel();
    if(tab==='style')h+=field('Ширина окна','questionStyle.width','number','min="300" max="900"')+field('Положение X','questionStyle.x','number','min="0" max="900"')+field('Положение Y','questionStyle.y','number','min="85" max="400"')+field('Цвет окна','questionStyle.background','color')+field('Цвет текста','questionStyle.color','color')+field('Кнопки и рамка','questionStyle.accent','color')+field('Размер текста','questionStyle.fontSize','number','min="16" max="44"')+select('Шрифт','questionStyle.fontFamily',{Arial:'Arial',Georgia:'Georgia',Verdana:'Verdana','Trebuchet MS':'Trebuchet MS'})+field('Скругление','questionStyle.radius','range','min="0" max="45"')+field('Толщина рамки','questionStyle.border','number','min="0" max="8"')+check('Тень окна','questionStyle.shadow');
    if(tab==='scoring')h+=field('Жизни','scoring.lives','number','min="1" max="10"')+field('Символ жизни','scoring.lifeIcon')+media('Своя иконка жизни','scoring.lifeAsset')+check('Случайный порядок заданий','scoring.random')+check('Включить таймер','scoring.timer')+select('Режим таймера','scoring.timerMode',{question:'На каждое задание',total:'На всю игру'})+field('Время, секунды','scoring.seconds','number','min="30" max="3600"')+select('Когда время закончилось','scoring.timeout',{life:'Снять жизнь и перейти дальше',end:'Завершить игру',extend:'Добавить 30 секунд'})+field('Бонус за серию (0 = выключить)','scoring.bonusEvery','number','min="0" max="100"')+field('Бонусные баллы','scoring.bonusPoints','number','min="0" max="10000"')+help('Баллы за ответ задаются отдельно в каждом задании. Во время анимации и паузы таймер остановлен.');
    if(tab==='audio'){h+=field('Общая громкость, %','audio.volume','range','min="0" max="100"')+check('Эффекты','audio.effects')+check('Музыка','audio.music')+help('Без загрузки используются короткие встроенные сигналы. Музыка и звук начинают работать после нажатия «Играть».');for(const [event,label] of Object.entries(soundEvents))h+=media(label,'audio.assets.'+event,true)}
    if(tab==='final')for(const [key,label] of [['winScreen','Победа'],['loseScreen','Повторная попытка']])h+=`<h3>${label}</h3><button data-screen="${key==='winScreen'?'win':'lose'}">Показать экран</button>`+field('Заголовок (пусто = перевод)',key+'.title')+area('Подзаголовок',key+'.subtitle')+field('Цвет фона',key+'.color','color')+media('Фон / GIF',key+'.background');
    if(tab==='accessibility')h+=check('Уменьшить анимацию','accessibility.reducedMotion')+check('Высокий контраст','accessibility.contrast')+field('Масштаб текста задания','accessibility.textScale','range','min="1" max="1.5" step="0.05"')+help('Системный prefers-reduced-motion учитывается автоматически. Все задания доступны с клавиатуры; в сортировке используйте кнопки ↑ и ↓. Игрок может остановить игру и добавить время.')+help('В редакторе: стрелки — сдвиг на 1 px, Shift + стрелки — на 10 px. Ctrl/⌘ Z — отмена. Ctrl/⌘ Shift Z — повтор.');
    if(tab==='export'){const errors=validation();h+='<div class="export-report">'+e(errors.length?errors.join('\n'):'✓ Проект готов к экспорту')+'</div>'+help('HTML содержит только игру, встроенные медиа и выбранный язык. Редактор, история изменений и авторский подвал в игру не попадают.')+`<div class="export-report">Проект: ${formatBytes(new Blob([JSON.stringify(project)]).size)}\nАвтономная игра: ${formatBytes(new Blob([exportHTML()]).size)}</div>`+'<div class="panel-actions"><button data-action="export">Скачать HTML</button><button data-action="copy">Копировать для Genially</button></div>'+help('Genially может ограничивать вставку скриптов и размер кода. Для надёжного встраивания опубликуйте экспортированный HTML на GitHub Pages и вставьте его URL как iframe.');}
    $('settings').innerHTML=h;bindSettings();
  }
  function questionsPanel(){let h='<div class="panel-actions"><button data-action="add-question">+ Добавить задание</button></div>';project.questions.forEach((q,i)=>{h+=`<div class="q-card ${q.id===selectedQ?'selected':''}"><button data-question="${e(q.id)}">${i+1}. ${e(q.prompt.slice(0,90))}</button><p class="help">${B.types[q.type]} · ${q.points} баллов</p><div class="panel-actions"><button data-q-action="up" data-id="${e(q.id)}" ${i===0?'disabled':''}>↑</button><button data-q-action="down" data-id="${e(q.id)}" ${i===project.questions.length-1?'disabled':''}>↓</button><button data-q-action="duplicate" data-id="${e(q.id)}">Копия</button><button data-q-action="delete" data-id="${e(q.id)}" class="danger">Удалить</button></div></div>`});const i=project.questions.findIndex(q=>q.id===selectedQ);if(i<0)return h;const q=project.questions[i],path=`questions.${i}`;h+='<h3>Редактирование задания</h3>'+select('Тип',path+'.type',B.types)+area('Текст задания',path+'.prompt')+media('Изображение / GIF к заданию',path+'.asset')+field('Баллы',path+'.points','number','min="0" max="10000"')+area('Пояснение после ответа',path+'.explanation');
    if(['single','multiple','order'].includes(q.type)){h+=help(q.type==='order'?'Правильный порядок соответствует списку ниже. Перед показом ученику элементы перемешиваются.':'Отметьте правильные ответы.');q.options.forEach((o,j)=>{const op=path+`.options.${j}`;h+=`<div class="option-edit">`+field('Вариант '+(j+1),op+'.text')+(q.type!=='order'?check('Правильный',op+'.correct'):'' )+media('Изображение варианта',op+'.asset')+`<div class="panel-actions"><button data-option-action="up" data-index="${j}" ${j===0?'disabled':''}>↑</button><button data-option-action="down" data-index="${j}" ${j===q.options.length-1?'disabled':''}>↓</button><button data-option-action="delete" data-index="${j}">Удалить</button></div></div>`});h+='<button data-action="add-option">+ Вариант ответа</button>';if(q.type!=='order')h+=check('Перемешивать варианты',path+'.shuffle')}
    if(q.type==='text')h+=`<label class="field"><span>Допустимые ответы — каждый с новой строки</span><textarea data-answers="${i}">${e(q.answers.join('\n'))}</textarea></label>`+check('Учитывать регистр',path+'.caseSensitive')+field('Числовой допуск (0 = точное совпадение)',path+'.tolerance','number','min="0" step="0.01"');
    if(q.type==='oral')h+=select('Режим ответа',path+'.oralMode',{self:'Самопроверка: Верно / Неверно',continue:'Ответ дан — продолжить'});return h;
  }
  function bindSettings(){
    $('settings').querySelectorAll('[data-path]').forEach(el=>el.addEventListener(el.tagName==='TEXTAREA'||el.type==='text'||el.type==='color'||el.type==='range'?'input':'change',()=>{if(testing)stopTest();let value=el.type==='checkbox'?el.checked:['number','range'].includes(el.type)?Number(el.value):el.value;if(typeof value==='number'){if(!Number.isFinite(value))return;if(el.min!=='')value=Math.max(Number(el.min),value);if(el.max!=='')value=Math.min(Number(el.max),value);el.value=value}commit();const path=el.dataset.path;set(path,value);if(path.endsWith('.correct')&&value){const m=path.match(/^questions\.(\d+)\.options\.(\d+)\.correct$/);if(m&&project.questions[m[1]].type==='single')project.questions[m[1]].options.forEach((o,i)=>o.correct=i===Number(m[2]))}if(path.endsWith('.type')){const q=project.questions[Number(path.split('.')[1])];if(q.type==='single')q.options.forEach((o,i)=>o.correct=i===0)}changed(path==='language'||path.endsWith('.type')||path.endsWith('.correct'))}));
    $('settings').querySelectorAll('[data-answers]').forEach(el=>el.onchange=()=>{commit();project.questions[el.dataset.answers].answers=el.value.split('\n').map(s=>s.trim()).filter(Boolean);changed()});
    $('settings').querySelectorAll('[data-media]').forEach(el=>el.onchange=()=>{if(el.files[0])upload(el.files[0],el.dataset.media)});
    $('settings').querySelectorAll('[data-clear-media]').forEach(el=>el.onclick=()=>{commit();set(el.dataset.clearMedia,'');changed(true)});
    $('settings').querySelectorAll('[data-object]').forEach(el=>el.onclick=()=>{selected=el.dataset.object;renderPreview();renderInspector();if(tab==='scene')renderSettings()});
    $('settings').querySelectorAll('[data-question]').forEach(el=>el.onclick=()=>{selectedQ=el.dataset.question;renderSettings();renderPreview()});
    $('settings').querySelectorAll('[data-q-action]').forEach(el=>el.onclick=()=>questionAction(el.dataset.qAction,el.dataset.id));
    $('settings').querySelectorAll('[data-option-action]').forEach(el=>el.onclick=()=>optionAction(el.dataset.optionAction,Number(el.dataset.index)));
    $('settings').querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action));
    $('settings').querySelectorAll('[data-screen]').forEach(el=>el.onclick=()=>renderPreview(el.dataset.screen));
  }
  function action(a){if(a==='export')return downloadGame();if(a==='copy')return copyCode();if(a==='add-question'){commit();const q=B.question();project.questions.push(q);selectedQ=q.id;changed(true)}if(a==='add-option'){const q=project.questions.find(q=>q.id===selectedQ);if(!q)return;commit();q.options.push({id:B.uid(),text:'Новый вариант',correct:false,asset:''});changed(true)}if(a==='add-decor'){commit();const o={...B.clone(project.scene.objects.find(o=>o.id==='ball')),id:B.uid(),name:'Декорация',kind:'decor',x:500,y:100,w:90,h:90,z:2,asset:''};project.scene.objects.push(o);selected=o.id;changed(true)}}
  function questionAction(a,id){const i=project.questions.findIndex(q=>q.id===id);if(i<0)return;commit();if(a==='delete'){project.questions.splice(i,1);selectedQ=project.questions[Math.min(i,project.questions.length-1)]?.id||''}if(a==='duplicate'){const q=B.clone(project.questions[i]);q.id=B.uid();q.options.forEach(o=>o.id=B.uid());project.questions.splice(i+1,0,q);selectedQ=q.id}if(a==='up'||a==='down'){const j=i+(a==='up'?-1:1);if(j>=0&&j<project.questions.length)[project.questions[i],project.questions[j]]=[project.questions[j],project.questions[i]]}changed(true)}
  function optionAction(a,i){const q=project.questions.find(q=>q.id===selectedQ);if(!q)return;commit();if(a==='delete')q.options.splice(i,1);else{const j=i+(a==='up'?-1:1);if(j>=0&&j<q.options.length)[q.options[i],q.options[j]]=[q.options[j],q.options[i]]}changed(true)}
  function renderPreview(screen){
    if(testing)return;game?.destroy();let mode=screen||(['title'].includes(tab)?'title':tab==='final'?'win':'court');
    const p=B.clone(project);if(['questions','style'].includes(tab)){const q=p.questions.find(q=>q.id===selectedQ)||p.questions[0];p.questions=q?[q]:[];p.titleScreen.enabled=false;p.scoring.timer=false;mode='question'}
    game=mountBasketball($('preview-root'),p,B,{editor:true,screen:mode==='question'?undefined:mode});
    $('screen-label').textContent={title:'Титульный лист',court:'Игровая площадка',question:'Окно задания',win:'Экран победы',lose:'Повторная попытка'}[mode];
    const scene=$('preview-root').querySelector('.game-scene');if(mode!=='court'&&mode!=='question')return;scene.classList.add('edit-scene');
    $('preview-root').querySelectorAll('[data-object]').forEach(el=>{const o=project.scene.objects.find(o=>o.id===el.dataset.object);el.dataset.locked=o.locked;el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',o.name);if(o.id===selected){el.classList.add('selected');if(!o.locked)for(const corner of ['nw','ne','sw','se']){const handle=document.createElement('button');handle.className='resize-handle';handle.dataset.corner=corner;handle.setAttribute('aria-label','Изменить размер '+corner);el.append(handle)}}el.onpointerdown=ev=>beginDrag(ev,o,el)});
  }
  function beginDrag(ev,o,el){if(ev.button!==0)return;ev.preventDefault();const isResize=ev.target.dataset.corner;selected=o.id;renderInspector();$('preview-root').querySelectorAll('.selected').forEach(n=>n.classList.remove('selected'));el.classList.add('selected');if(o.locked)return;
    const before=B.clone(o),startX=ev.clientX,startY=ev.clientY,scale=$('preview-root').clientWidth/1200;let moved=false;el.setPointerCapture(ev.pointerId);
    function move(event){let dx=(event.clientX-startX)/scale,dy=(event.clientY-startY)/scale;if(!moved&&Math.abs(dx)+Math.abs(dy)<2)return;if(!moved){commit();moved=true}if(isResize){const west=isResize.includes('w'),north=isResize.includes('n');let w=Math.max(20,before.w+(west?-dx:dx)),h=Math.max(20,before.h+(north?-dy:dy));if(event.shiftKey){const ratio=before.w/before.h;if(Math.abs(dx)>Math.abs(dy))h=w/ratio;else w=h*ratio}o.w=Math.round(w);o.h=Math.round(h);o.x=Math.round(before.x+(west?before.w-w:0));o.y=Math.round(before.y+(north?before.h-h:0))}else{o.x=Math.round(Math.max(-o.w+20,Math.min(1180,before.x+dx)));o.y=Math.round(Math.max(-o.h+20,Math.min(655,before.y+dy)))}Object.assign(el.style,{left:o.x+'px',top:o.y+'px',width:o.w+'px',height:o.h+'px'});renderInspector()}
    function end(){el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);renderPreview();if(moved)scheduleSave();if(tab==='scene')renderSettings()}
    el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);
  }
  function renderInspector(){const o=project.scene.objects.find(o=>o.id===selected);if(testing){$('inspector').innerHTML='<h3>Режим игры</h3><p class="help">Ответьте на задания, чтобы проверить броски, таймер и финальные экраны. Для изменений нажмите «Редактировать».</p>';return}if(!o){$('inspector').innerHTML='<h3>Выберите объект на сцене</h3>';return}const i=project.scene.objects.indexOf(o),path=`scene.objects.${i}`;$('inspector').innerHTML=`<h3>Выбран объект: ${e(o.name)}</h3><div class="inspector-grid">`+[['X','x',-2400,2400],['Y','y',-1350,1350],['Ширина','w',20,2400],['Высота','h',20,1350],['Поворот','rotation',-360,360],['Прозрачн.','opacity',0,1],['Слой','z',0,50]].map(([label,key,min,max])=>field(label,path+'.'+key,'number',`min="${min}" max="${max}" step="${key==='opacity'?'.05':'1'}" ${o.locked?'disabled':''}`)).join('')+`</div><div class="panel-actions"><button data-obj-action="front">Вперёд</button><button data-obj-action="back">Назад</button><button data-obj-action="lock">${o.locked?'Разблокировать':'Блокировать'}</button><button data-obj-action="hide">${o.hidden?'Показать':'Скрыть'}</button><button data-obj-action="duplicate" ${o.kind==='hud'?'disabled':''}>Дублировать</button><button data-obj-action="delete" ${o.kind!=='decor'?'disabled title="Обязательный объект игры"':''}>Удалить</button></div>`;
    $('inspector').querySelectorAll('[data-path]').forEach(el=>el.onchange=()=>{const v=Math.max(Number(el.min),Math.min(Number(el.max),Number(el.value)));if(!Number.isFinite(v))return;commit();set(el.dataset.path,v);changed()});
    $('inspector').querySelectorAll('[data-obj-action]').forEach(el=>el.onclick=()=>{commit();switch(el.dataset.objAction){case 'front':o.z=Math.min(50,o.z+1);break;case 'back':o.z=Math.max(0,o.z-1);break;case 'lock':o.locked=!o.locked;break;case 'hide':o.hidden=!o.hidden;break;case 'duplicate':const c=B.clone(o);c.id=B.uid();c.art=o.art||o.kind;c.kind='decor';if(o.kind==='player')c.asset=o.asset||project.player.idle;c.name=o.name+' (копия)';c.x+=25;c.y+=25;c.locked=false;project.scene.objects.push(c);selected=c.id;break;case 'delete':if(o.kind==='decor'){project.scene.objects.splice(i,1);selected='player'}break}changed(tab==='scene')});
  }
  function renderAll(){if(!project.questions.some(q=>q.id===selectedQ))selectedQ=project.questions[0]?.id||'';renderSettings();renderPreview();renderInspector();buttons();size()}
  function startTest(){const errors=validation();if(errors.length)return showErrors(errors);testing=true;game?.destroy();game=mountBasketball($('preview-root'),project);$('screen-label').textContent='Тестирование игры';buttons();renderInspector()}
  function stopTest(){testing=false;renderAll()}
  function formatBytes(n){return n<1024?n+' Б':n<1048576?(n/1024).toFixed(1)+' КБ':(n/1048576).toFixed(2)+' МБ'}
  function size(){$('size-status').textContent=project.questions.length+' заданий · '+formatBytes(new Blob([JSON.stringify(project)]).size)}
  async function upload(file,path){
    const rev=revision;const audio=/^audio/.test(file.type)||/\.(mp3|wav|ogg)$/i.test(file.name);const type=audio?(file.type||(/\.ogg$/i.test(file.name)?'audio/ogg':/\.wav$/i.test(file.name)?'audio/wav':'audio/mpeg')):file.type;
    if(!/^(image\/(png|jpeg|webp|gif)|audio\/(mpeg|mp3|wav|x-wav|ogg))$/.test(type))return toast('Допустимы PNG, JPEG, WebP, GIF и MP3, WAV, OGG.');if(file.size>25*1048576)return toast('Файл больше 25 МБ. Уменьшите его перед загрузкой.');
    toast('Загружаю медиа…');try{let data=await readData(file),blob=file;if(!audio&&type!=='image/gif'){const image=await loadImage(data);const max={balanced:1600,high:2400,small:1000}[project.meta.quality];const scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const optimized=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.84));if(optimized&&optimized.size<file.size){blob=optimized;data=await readData(optimized)}}if(rev!==revision)return toast('Проект изменился во время загрузки. Выберите файл ещё раз.');if(testing)stopTest();commit();const id=B.uid();project.assets[id]={name:file.name,type:blob.type||type,data,size:blob.size,originalSize:file.size};if(audio&&!/^data:audio\//.test(data))project.assets[id].data='data:'+type+data.slice(data.indexOf(';'));set(path,id);changed(true);toast(type==='image/gif'?'GIF сохранён с анимацией'+(file.size>3*1048576?' · крупный файл, проверьте размер экспорта.':'.'):'Медиа добавлено: '+formatBytes(file.size)+' → '+formatBytes(blob.size))}catch(err){toast('Не удалось загрузить медиа: '+err.message)}
  }
  const readData=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});
  const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Не удалось прочитать изображение'));i.src=src});
  function validation(){const errors=B.validate(project);const clean=B.compact(project);for(const [id,a] of Object.entries(clean.assets))if(!B.allowedAsset(a))errors.push('Некорректное медиа: '+a.name);const refs=new Set([project.scene.background,project.titleScreen.background,project.winScreen.background,project.loseScreen.background,project.player.idle,project.player.success,project.player.miss,project.scoring.lifeAsset,...project.scene.objects.map(o=>o.asset),...project.questions.flatMap(q=>[q.asset,...q.options.map(o=>o.asset)]),...Object.values(project.audio.assets)].filter(Boolean));refs.forEach(id=>{if(!project.assets[id])errors.push('Медиа не найдено: '+id)});return errors}
  function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
  const safeJSON=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  function exportHTML(){const p=B.compact(project);const lang=B.words[p.language]||B.words.ru;const script='const Basketball={clone:'+B.clone.toString()+',escape:'+B.escape.toString()+',check:'+B.check.toString()+',words:'+safeJSON({[p.language]:lang})+'};';const runtime=project.exportSettings.light?BUNDLE.game.split('\n').map(line=>line.trim()).filter(line=>line&&!line.startsWith('//')).join('\n'):BUNDLE.game;const css=project.exportSettings.light?BUNDLE.css.replace(/\s+/g,' ').replace(/\s*([{}:;,])\s*/g,'$1'):BUNDLE.css;return '<!doctype html>\n<html lang="'+e(p.language)+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(p.meta.name)+'</title><style>html,body{margin:0;background:#102c35;min-height:100%;display:grid;place-items:center}body{width:100%}#game{width:min(100vw,177.777vh)}'+css+'</style></head><body><main id="game" aria-label="'+e(p.meta.name)+'"></main><script>'+script+'\n'+runtime+'\nmountBasketball(document.getElementById("game"),'+safeJSON(p)+');<\/script></body></html>'}
  function downloadGame(){const errors=validation();if(errors.length)return showErrors(errors);const html=exportHTML();download('basketball-game.html',html,'text/html');toast('Игра скачана: '+formatBytes(new Blob([html]).size))}
  async function copyCode(){const errors=validation();if(errors.length)return showErrors(errors);const html=exportHTML();const code='<iframe title="'+e(project.meta.name)+'" style="width:100%;aspect-ratio:16/9;border:0" allow="autoplay; fullscreen" allowfullscreen srcdoc="'+e(html)+'"></iframe>';try{await navigator.clipboard.writeText(code);toast('Код iframe скопирован · '+formatBytes(new Blob([code]).size))}catch{modal('Код для Genially','Буфер обмена недоступен. Выделите и скопируйте код вручную.',`<textarea id="manual-copy" readonly aria-label="Код для вставки">${e(code)}</textarea>`,[{label:'Закрыть',action:closeModal}]);$('manual-copy').select()}}
  function optimize(){commit();const before=new Blob([JSON.stringify(project)]).size;project=B.compact(project);project.exportSettings.light=true;changed(true);toast('Неиспользуемые медиа удалены: '+formatBytes(before)+' → '+formatBytes(new Blob([JSON.stringify(project)]).size)+'. Экспорт уже исключает редактор и лишние языки.')}
  function modal(title,text,body='',actions=[]){const root=$('modal-root');root.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-card"><h2 id="modal-title">${e(title)}</h2><p class="help">${e(text)}</p>${body}<div class="panel-actions" id="modal-actions"></div></div></div>`;actions.forEach(({label,action})=>{const b=document.createElement('button');b.textContent=label;b.onclick=action;$('modal-actions').append(b)});root.querySelector('button,textarea')?.focus()}
  const closeModal=()=>{$('modal-root').innerHTML=''};
  function showErrors(errors){modal('Проверьте проект','Исправьте ошибки перед тестированием и экспортом.','<div class="export-report">'+e(errors.join('\n'))+'</div>',[{label:'Закрыть',action:closeModal}])}
  $('tabs').onclick=ev=>{const key=ev.target.dataset.tab;if(!key)return;if(testing){testing=false;game?.destroy()}tab=key;if(key==='player')selected='player';if(key==='equipment')selected='hoop';if(key==='scoring')selected='hud';renderAll()};
  $('save-project').onclick=()=>{const p=B.compact(project);download('project.basketball.json',JSON.stringify(p,null,2),'application/json');toast('Проект сохранён вместе с медиа')};
  $('load-project').onclick=()=>{$('project-file').value='';$('project-file').click()};
  $('project-file').onchange=async()=>{const f=$('project-file').files[0];if(!f)return;if(f.size>100*1048576)return toast('Проект слишком большой (лимит 100 МБ).');try{const p=B.load(JSON.parse(await f.text()));if(testing){testing=false;game?.destroy()}commit();project=p;selectedQ=p.questions[0]?.id||'';selected='player';renderAll();scheduleSave();toast('Проект восстановлен')}catch(err){toast('Ошибка проекта: '+err.message)}};
  $('export-html').onclick=downloadGame;$('optimize').onclick=optimize;$('copy-code').onclick=copyCode;$('undo').onclick=undo;$('redo').onclick=redo;$('test').onclick=startTest;$('preview').onclick=stopTest;
  document.addEventListener('keydown',ev=>{if($('modal-root').firstChild){if(ev.key==='Escape')closeModal();if(ev.key==='Tab'){const controls=[...$('modal-root').querySelectorAll('button,textarea')];if(ev.shiftKey&&document.activeElement===controls[0]){ev.preventDefault();controls.at(-1).focus()}else if(!ev.shiftKey&&document.activeElement===controls.at(-1)){ev.preventDefault();controls[0].focus()}}return}const textInput=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'&&!textInput){ev.preventDefault();ev.shiftKey?redo():undo();return}if(testing||textInput)return;const o=project.scene.objects.find(o=>o.id===selected);if(!o||o.locked)return;const delta=ev.shiftKey?10:1;const moves={ArrowLeft:[-delta,0],ArrowRight:[delta,0],ArrowUp:[0,-delta],ArrowDown:[0,delta]};if(moves[ev.key]){ev.preventDefault();commit();o.x+=moves[ev.key][0];o.y+=moves[ev.key][1];changed()}});
  async function initStorage(){try{db=await new Promise((resolve,reject)=>{const request=indexedDB.open('basketball-editor',1);request.onupgradeneeded=()=>request.result.createObjectStore('projects');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});const saved=await new Promise((resolve,reject)=>{const req=db.transaction('projects','readonly').objectStore('projects').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});if(saved&&revision===0)modal('Продолжить редактирование?','На этом устройстве найден сохранённый проект «'+saved.meta.name+'».','',[{label:'Продолжить редактирование',action:()=>{try{project=B.load(saved);renderAll();closeModal();toast('Автосохранение восстановлено')}catch(err){closeModal();toast(err.message)}}},{label:'Начать заново',action:()=>{closeModal();persist()}}])}catch{$('save-status').textContent='Автосохранение недоступно. Скачивайте JSON-проект.'}}
  renderAll();initStorage();
})();
